CREATE TABLE auth_user
(
    auth_id    VARCHAR(36)  NOT NULL COMMENT 'UUID del flow: 0e8400-e29b-41d4-a716-446655440000',
    phone      VARCHAR(254) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);